import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'
import '@quasar/extras/material-icons-outlined/material-icons-outlined.css'
import '@quasar/extras/material-icons-round/material-icons-round.css'
import '@quasar/extras/material-icons-sharp/material-icons-sharp.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'

import {
  ClosePopup,
  Dialog,
  Loading,
  Notify,
  QAvatar,
  QBar,
  QBreadcrumbs,
  QBreadcrumbsEl,
  QBtn,
  QBtnToggle,
  QCard,
  QCardActions,
  QCardSection,
  QCheckbox,
  QDialog,
  QDrawer,
  QExpansionItem,
  QForm,
  QHeader,
  QIcon,
  QImg,
  QInput,
  QItem,
  QItemLabel,
  QItemSection,
  QLayout,
  QLinearProgress,
  QList,
  QMenu,
  QPage,
  QPageContainer,
  QRouteTab,
  QScrollArea,
  QSeparator,
  QSpace,
  QSplitter,
  QTab,
  QTable,
  QTabs,
  QTd,
  QTh,
  QToolbar,
  QToolbarTitle,
  QTooltip,
  QTr,
  Quasar,
  Ripple,
} from 'quasar'
import Vue from 'vue'

Vue.use(Quasar, {
  components: {
    QAvatar,
    QBar,
    QBreadcrumbs,
    QBreadcrumbsEl,
    QBtn,
    QBtnToggle,
    QCard,
    QCardActions,
    QCardSection,
    QCheckbox,
    QDialog,
    QDrawer,
    QExpansionItem,
    QForm,
    QHeader,
    QIcon,
    QImg,
    QInput,
    QItem,
    QItemLabel,
    QItemSection,
    QLayout,
    QLinearProgress,
    QList,
    QMenu,
    QPage,
    QPageContainer,
    QRouteTab,
    QScrollArea,
    QSeparator,
    QSpace,
    QSplitter,
    QTab,
    QTable,
    QTabs,
    QTd,
    QTh,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    QTr,
  },
  config: {
    notify: {},
    loading: {},
    screen: {
      bodyClasses: true,
    },
  },
  directives: {
    ClosePopup,
    Ripple,
  },
  plugins: {
    Dialog,
    Loading,
    Notify,
  },
})
